version: '3.3'

volumes:
  pg_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: dron71/foodgram_backend:v9.2
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: dron71/foodgram_frontend:v9.2
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: dron71/foodgram_gateway:v9.2
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
